### ISSUE TITLE
Lỗi

### ISSUE THREAD

**Issue by ayakaa-chan** [zijipia/ZiExtractor#5]
Update xong là nó lỗi vậy á ☠
```
[YOUTUBEJS][Text]: Unable to find matching run for command run. Skipping... {
  command_run: { startIndex: 0, length: 57, onTap: { innertubeCommand: [Object] } },
  input_data: {
    content: 'Jack | Hoa Hải Đường | Official Music Video · 4:13',
    commandRuns: [ [Object] ]
  },
  parsed_runs: [
    {
      text: 'Jack | Hoa Hải Đường | Official Music Video · 4:13',
      startIndex: 0
    }
  ]
}
[YOUTUBEJS][Text]: Unable to find matching run for command run. Skipping... {
  command_run: { startIndex: 0, length: 54, onTap: { innertubeCommand: [Object] } },
  input_data: {
    content: 'SÓNG GIÓ | ICM x JACK | OFFICIAL MUSIC VIDEO · 5:51',
    commandRuns: [ [Object] ]
  },
  parsed_runs: [
    {
      text: 'SÓNG GIÓ | ICM x JACK | OFFICIAL MUSIC VIDEO · 5:51',
      startIndex: 0
    }
  ]
}
[YOUTUBEJS][Text]: Unable to find matching run for command run. Skipping... {
  command_run: { startIndex: 0, length: 57, onTap: { innertubeCommand: [Object] } },
  input_data: {
    content: 'Jack | Hoa Hải Đường | Official Music Video · 4:13',
    commandRuns: [ [Object] ]
  },
  parsed_runs: [
    {
      text: 'Jack | Hoa Hải Đường | Official Music Video · 4:13',
      startIndex: 0
    }
  ]
}
[YOUTUBEJS][Text]: Unable to find matching run for command run. Skipping... {
  command_run: { startIndex: 0, length: 54, onTap: { innertubeCommand: [Object] } },
  input_data: {
    content: 'SÓNG GIÓ | ICM x JACK | OFFICIAL MUSIC VIDEO · 5:51',
    commandRuns: [ [Object] ]
  },
  parsed_runs: [
    {
      text: 'SÓNG GIÓ | ICM x JACK | OFFICIAL MUSIC VIDEO · 5:51',
      startIndex: 0
    }
  ]
}
Unhandled promise rejection: TypeError: terminated
    at Fetch.onAborted (C:\Users\Admin\Desktop\Ziji\node_modules\undici\lib\fetch\index.js:1939:49)
    at Fetch.emit (node:events:519:28)
    at Fetch.terminate (C:\Users\Admin\Desktop\Ziji\node_modules\undici\lib\fetch\index.js:94:10)
    at Object.onError (C:\Users\Admin\Desktop\Ziji\node_modules\undici\lib\fetch\index.js:2110:34)
    at Request.onError (C:\Users\Admin\Desktop\Ziji\node_modules\undici\lib\core\request.js:330:27)
    at errorRequest (C:\Users\Admin\Desktop\Ziji\node_modules\undici\lib\client.js:2276:13)
    at TLSSocket.onSocketClose (C:\Users\Admin\Desktop\Ziji\node_modules\undici\lib\client.js:1152:5)
    at TLSSocket.emit (node:events:531:35)
    at node:net:339:12
    at TCP.done (node:_tls_wrap:657:7) {
  [cause]: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:218:20)
      at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
}
```

**Comment by zijipia** [comment]
này nhìn như lỗi của youtubei.js á để tui coi lại :3

**Comment by zijipia** [comment]
hm... vẫn bình thường mà ta... đâu ông thử debug player thử ik.
ở file index.js
```js
player.on('debug', console.log);
```
